require './job'
require 'resque'
require 'redis'
require "resque/tasks"

Resque.redis = Redis.new 

desc "Enqueue successful job"
task :enqueue_success do
  count = ENV['SUCCESS_JOBS'] || 1
  count.to_i.times do
    Resque.enqueue(Job, {})
  end
end

desc "Enqueue failing job"
task :enqueue_failure do
  count = ENV['FAILURE_JOBS'] || 1
  count.to_i.times do
    Resque.enqueue(FailingJob, {})
  end
end

desc "Enqueue a random sample of jobs"
task :enqueue_random_sample do
  job_klasses = Object.constants.select {|s| s.to_s.match(/Job\z/)}
  job_klasses.each do |klass|
    (rand(5) + 1).times { Resque.enqueue(Object.const_get(klass), {}) }
  end
end
